### ISSUE TITLE
cmake generating error. "format is not a member of std."

### ISSUE THREAD

**Issue by RahulAwasthi314** [X1nto/Vencorded#1]
When i tried to debug the error manually. I find out the format is declared in <format> library. So I included it. But now the format is not recognised as a library, eventhough my cmake version is greater than 3.12(as requirement mentioned in CMakeLists.txt)
Current cmake version: 3.24.2
My system configurations: arch linux

**Comment by X1nto** [comment]
This shouldn't be an issue with Vencorded but rather your development setup I guess. Did you try `#include <format>`? What are you using as a generator? Please note that Vencorded uses C++20, see [the compiler support](https://en.cppreference.com/w/cpp/compiler_support/20).
